name: onlinre_polling
description: A web project developed by Team-1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#=================Firebase======================
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: any

#====================UI=========================
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  lottie: ^1.0.1
  font_awesome_flutter: ^9.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/lotties/
    - assets/svgs/backgrounds/
    - assets/svgs/illustrations/

#  fonts:
#    - family: Monteserrat
#      fonts:
#        - asset: fonts/Montserrat-Black.ttf
#        - asset: fonts/Montserrat-BlackItalic.ttf
#        - asset: fonts/Montserrat-Bold.ttf
#        - asset: fonts/Montserrat-BoldItalic.ttf
#        - asset: fonts/Montserrat-ExtraBold.ttf
#        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
#        - asset: fonts/Montserrat-ExtraLight.ttf
#        - asset: fonts/Montserrat-ExtraLightItalic.ttf
#        - asset: fonts/Montserrat-Italic.ttf
#        - asset: fonts/Montserrat-Light.ttf
#        - asset: fonts/Montserrat-LightItalic.ttf
#        - asset: fonts/Montserrat-Medium.ttf
#        - asset: fonts/Montserrat-MediumItalic.ttf
#        - asset: fonts/Montserrat-Regular.ttf
#        - asset: fonts/Montserrat-SemiBold.ttf
#        - asset: fonts/Montserrat-SemiBoldItalic.ttf
#        - asset: fonts/Montserrat-Thin.ttf
#        - asset: fonts/Montserrat-ThinItalic.ttf