import 'package:flutter/material.dart';

class Diver {
  String firstName;
  String middleName;
  String lastName;
  String phoneNumber;
  String nationality;
  String gender;
  bool hasInsurance;
  String units;
  String currency;
  String insuranceName;
  String insuranceProvider;
  String insuranceDate;
  String policyNumber;
  String bloodGroup;
  String allergies;
  String otherConditions;
  String emergencyName;
  String emergencyEmail;
  String emergencyRelation;
  String emergencyMobile;
  String createdAt;
  String deletedAt;
  String displayName;
  String email;
  bool emailVerified;
  bool isActive;
  String highestDiveCertification;
  int totalDives;
  String lastDiveDate;
  String lastDiveLocation;
  String houseNo;
  String streetName;
  String cityName;
  String stateName;
  String zipCode;
  String address;
  String bio;
  String photoURL;
  bool publicProfile;
  bool allowOtherProfile;
  bool showNearby;
  bool notifications;
  bool privateAccount;
  int diveSitesNumber;
  int diveDestinationNumber;
  int deepestDive;
  int longestDive;
  int certificationNumber;

  Diver({
    @required this.diveSitesNumber,
    @required this.diveDestinationNumber,
    @required this.deepestDive,
    @required this.longestDive,
    @required this.certificationNumber,
    @required this.notifications,
    @required this.photoURL,
    @required this.publicProfile,
    @required this.privateAccount,
    @required this.allowOtherProfile,
    @required this.showNearby,
    @required this.createdAt,
    @required this.deletedAt,
    @required this.displayName,
    @required this.email,
    @required this.emailVerified,
    @required this.isActive,
    @required this.houseNo,
    @required this.streetName,
    @required this.cityName,
    @required this.stateName,
    @required this.zipCode,
    @required this.address,
    @required this.bio,
    @required this.firstName,
    @required this.middleName,
    @required this.lastName,
    @required this.highestDiveCertification,
    @required this.totalDives,
    @required this.lastDiveDate,
    @required this.lastDiveLocation,
    @required this.phoneNumber,
    @required this.nationality,
    @required this.units,
    @required this.currency,
    @required this.gender,
    @required this.hasInsurance,
    @required this.insuranceName,
    @required this.insuranceProvider,
    @required this.insuranceDate,
    @required this.policyNumber,
    @required this.bloodGroup,
    @required this.allergies,
    @required this.otherConditions,
    @required this.emergencyName,
    @required this.emergencyEmail,
    @required this.emergencyRelation,
    @required this.emergencyMobile,
  });
}
